sudo: false
language: python
python: 3.5
env:
    - TOXENV=flake8
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - pip install tox
script:
    - tox
after_success:
    coveralls
